name = "my-store"
pages_build_output_dir = "public"

# Bindings for KV and R2
[[kv_namespaces]]
binding = "ORDERS_KV"
id = "<YOUR_KV_NAMESPACE_ID>"

[[r2_buckets]]
binding = "CUSTOM_UPLOADS"
bucket_name = "<YOUR_R2_BUCKET_NAME>"

# Environment Variables (Public/Non-encrypted config)
[vars]
YOCO_PUBLIC_KEY = "pk_test_9e87d40f5E4Mmokee984"
YOCO_SECRET_KEY = "sk_test_ad3574baP4560Lq3f0b40ab9d9a7"
